# Generated by Django 3.1 on 2020-09-11 04:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, verbose_name='опубликовать')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата добавления')),
                ('topic', models.CharField(choices=[('news', 'новости'), ('about', 'о питомнике'), ('varieties', 'разновидности'), ('colors', 'окрасы'), ('markings', 'маркировки')], max_length=16, null=True, verbose_name='назначение')),
                ('title', models.CharField(max_length=64, null=True, verbose_name='заголовок')),
                ('text', models.TextField(max_length=2048, verbose_name='текст записи')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Новости и контент',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page', models.BooleanField(default=False, verbose_name='на главной странице')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата публикации')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('picture', models.ImageField(upload_to='images', verbose_name='фото')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.entry', verbose_name='запись')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
    ]
