# Generated by Django 3.1.1 on 2020-09-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.CharField(choices=[('news', 'новости'), ('about', 'о питомнике'), ('contract', 'договор'), ('varieties', 'разновидности'), ('colors', 'окрасы'), ('markings', 'маркировки')], max_length=16, null=True, verbose_name='назначение'),
        ),
    ]
