# Generated by Django 3.1 on 2020-08-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200830_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
