# Generated by Django 3.1 on 2020-08-31 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200831_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата публикации'),
        ),
    ]
