# Generated by Django 3.1 on 2020-09-01 04:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_image_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='название')),
                ('number', models.CharField(max_length=16, verbose_name='номер')),
                ('date_of_birth', models.DateField(default=datetime.date.today, verbose_name='дата рождения')),
            ],
            options={
                'verbose_name': 'Литера',
                'verbose_name_plural': 'Литеры',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=32, verbose_name='страна')),
                ('city', models.CharField(max_length=32, verbose_name='город')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='имя')),
                ('second_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='отчество')),
                ('last_name', models.CharField(max_length=32, verbose_name='фамилия')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='website.location', verbose_name='место проживания')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
            },
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('female_name', models.CharField(max_length=32, verbose_name='приставка для самки')),
                ('male_name', models.CharField(max_length=32, verbose_name='приставка для самца')),
                ('suffix', models.BooleanField(default=True, verbose_name='после клички')),
            ],
            options={
                'verbose_name': 'Приставка питомника',
                'verbose_name_plural': 'Приставки питомников',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.CharField(max_length=256, verbose_name='текст новости'),
        ),
        migrations.CreateModel(
            name='Rat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False, verbose_name='опубликовать')),
                ('status', models.CharField(choices=[('свободен', 'свободен'), ('зарезервирован', 'зарезервирован'), ('у владельца', 'у владельца')], default='у владельца', max_length=14, verbose_name='статус')),
                ('date_of_add', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('name', models.CharField(max_length=32, verbose_name='кличка')),
                ('variety', models.CharField(max_length=128, verbose_name='разновидность')),
                ('gender', models.CharField(choices=[('самец', 'самец'), ('самка', 'самка')], default='самец', max_length=5, verbose_name='пол')),
                ('title', models.CharField(choices=[('нет', 'без титула'), ('чемпион', 'чемпион'), ('грандчемпион', 'грандчемпион')], default='нет', max_length=12, verbose_name='титул')),
                ('date_of_birth', models.DateField(default=datetime.date.today, verbose_name='дата рождения')),
                ('date_of_death', models.DateField(blank=True, default=None, null=True, verbose_name='дата смерти')),
                ('information', models.TextField(max_length=1024, verbose_name='информация')),
                ('breeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rats_bred', to='website.person', verbose_name='заводчик')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathers_children', to='website.rat', verbose_name='отец')),
                ('litter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='babies', to='website.litter', verbose_name='литера')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothers_children', to='website.rat', verbose_name='мать')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rats_own', to='website.person', verbose_name='владелец')),
                ('prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rats', to='website.prefix', verbose_name='приставка')),
            ],
            options={
                'verbose_name': 'Крыса',
                'verbose_name_plural': 'Крысы',
            },
        ),
        migrations.AddField(
            model_name='litter',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters', to='website.person', verbose_name='заводчик'),
        ),
        migrations.AddField(
            model_name='litter',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_litters', to='website.rat', verbose_name='отец'),
        ),
        migrations.AddField(
            model_name='litter',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_litters', to='website.rat', verbose_name='мать'),
        ),
        migrations.AddField(
            model_name='litter',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters', to='website.prefix', verbose_name='приставка'),
        ),
        migrations.AddField(
            model_name='image',
            name='rat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.rat', verbose_name='крыса'),
        ),
    ]
