# Generated by Django 3.1 on 2020-09-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200901_0443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Заводчик/владелец', 'verbose_name_plural': 'Заводчики и владельцы'},
        ),
    ]
