# Generated by Django 3.1 on 2020-09-01 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200901_0507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='litter',
            options={'verbose_name': 'литеру', 'verbose_name_plural': 'Литеры'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'локацию', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'личность', 'verbose_name_plural': 'Заводчики и владельцы'},
        ),
        migrations.AlterModelOptions(
            name='prefix',
            options={'verbose_name': 'приставку', 'verbose_name_plural': 'Приставки питомников'},
        ),
        migrations.AlterModelOptions(
            name='rat',
            options={'verbose_name': 'крысу', 'verbose_name_plural': 'Крысы'},
        ),
    ]
