# Generated by Django 3.1 on 2020-09-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200901_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False, verbose_name='опубликовать')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('text', models.CharField(max_length=256, verbose_name='текст записи')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
