# Generated by Django 3.1 on 2020-09-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(max_length=1024, verbose_name='текст записи'),
        ),
    ]
