# Generated by Django 3.1 on 2020-09-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_image_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rat',
            name='information',
            field=models.TextField(max_length=2048, verbose_name='информация'),
        ),
    ]
