# Generated by Django 3.1 on 2020-09-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200902_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rat',
            name='information',
            field=models.TextField(verbose_name='информация'),
        ),
    ]
