# Generated by Django 3.1 on 2020-09-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200902_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(max_length=2048, verbose_name='текст записи'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='information',
            field=models.TextField(max_length=2048, verbose_name='информация'),
        ),
    ]
