# Generated by Django 3.1 on 2020-09-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200902_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.CharField(choices=[('about', 'о питомнике'), ('varieties', 'разновидности')], max_length=16, null=True, verbose_name='назначение'),
        ),
    ]
