# Generated by Django 3.1 on 2020-09-03 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_entry_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'Новости и контент'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='дата добавления'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.CharField(choices=[('news', 'новости'), ('about', 'о питомнике'), ('varieties', 'разновидности')], max_length=16, null=True, verbose_name='назначение'),
        ),
    ]
