# Generated by Django 3.1 on 2020-09-03 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200903_0437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
