# Generated by Django 3.1 on 2020-09-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_delete_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=64, null=True, verbose_name='заголовок'),
        ),
    ]
