# Generated by Django 3.1 on 2020-09-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rat',
            name='gender',
            field=models.CharField(choices=[('male', 'самец'), ('female', 'самка')], default='самец', max_length=8, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='status',
            field=models.CharField(choices=[('свободен', 'свободен'), ('зарезервирован', 'зарезервирован'), ('у владельца', 'у владельца')], default='у владельца', max_length=16, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='title',
            field=models.CharField(choices=[('нет', 'без титула'), ('чемпион', 'чемпион'), ('грандчемпион', 'грандчемпион')], default='нет', max_length=16, verbose_name='титул'),
        ),
    ]
