# Generated by Django 3.1 on 2020-09-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200903_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rat',
            name='information',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='информация'),
        ),
    ]
