# Generated by Django 3.1 on 2020-09-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20200903_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litter',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='номер'),
        ),
    ]
