# Generated by Django 3.1 on 2020-09-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20200903_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rat',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='website.litter', verbose_name='литера'),
        ),
    ]
