# Generated by Django 3.1 on 2020-09-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_rat_in_rattery'),
    ]

    operations = [
        migrations.AddField(
            model_name='rat',
            name='castrate',
            field=models.BooleanField(default=False, verbose_name='кастрирован(а)'),
        ),
    ]
