# Generated by Django 3.1 on 2020-09-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_rat_castrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rat',
            name='gender',
            field=models.CharField(choices=[('самец', 'самец'), ('самка', 'самка')], default='самец', max_length=8, verbose_name='пол'),
        ),
    ]
