# Generated by Django 3.1 on 2020-09-04 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20200904_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rat',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_children', to='website.rat', verbose_name='отец'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_children', to='website.rat', verbose_name='мать'),
        ),
    ]
