# Generated by Django 3.1 on 2020-09-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20200904_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='rat',
            name='alive',
            field=models.BooleanField(default=True, verbose_name='жив(а)'),
        ),
    ]
