# Generated by Django 3.1 on 2020-09-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_rat_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='litter',
            name='year',
            field=models.CharField(default=2020, max_length=4, verbose_name='год рождения'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.CharField(choices=[('news', 'новости'), ('about', 'о питомнике'), ('varieties', 'разновидности'), ('colors', 'окрасы'), ('markings', 'маркировки')], max_length=16, null=True, verbose_name='назначение'),
        ),
    ]
