# Generated by Django 3.1 on 2020-09-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20200907_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rat',
            name='gender',
            field=models.CharField(choices=[('male', 'самец'), ('female', 'самка')], default='male', max_length=8, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='status',
            field=models.CharField(choices=[('available', 'свободен'), ('reserved', 'зарезервирован'), ('owned', 'у владельца')], default='owned', max_length=16, verbose_name='статус'),
        ),
    ]
