# Generated by Django 3.1 on 2020-09-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20200907_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(max_length=322, null=True, verbose_name='регион'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=32, verbose_name='населенный пункт'),
        ),
        migrations.AlterField(
            model_name='rat',
            name='title',
            field=models.CharField(choices=[('none', 'без титула'), ('champion', 'чемпион'), ('grandchampion', 'грандчемпион')], default='none', max_length=16, verbose_name='титул'),
        ),
    ]
