# Generated by Django 3.1 on 2020-09-09 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20200908_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='прочитана')),
                ('approved', models.BooleanField(default=False, verbose_name='одобрена')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='дата заполнения')),
                ('name', models.CharField(max_length=64, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254)),
                ('text1', models.TextField(max_length=2048, verbose_name='ответ на вопрос №1')),
                ('text2', models.TextField(max_length=2048, verbose_name='ответ на вопрос №2')),
                ('text3', models.TextField(max_length=2048, verbose_name='ответ на вопрос №3')),
                ('text4', models.TextField(max_length=2048, verbose_name='ответ на вопрос №4')),
                ('text5', models.TextField(max_length=2048, verbose_name='ответ на вопрос №5')),
                ('text6', models.TextField(max_length=2048, verbose_name='ответ на вопрос №6')),
                ('text7', models.TextField(max_length=2048, verbose_name='ответ на вопрос №7')),
                ('text8', models.TextField(max_length=2048, verbose_name='ответ на вопрос №8')),
                ('text9', models.TextField(max_length=2048, verbose_name='ответ на вопрос №9')),
            ],
            options={
                'verbose_name': 'анкету',
                'verbose_name_plural': 'анкеты',
            },
        ),
    ]
