# Generated by Django 3.1 on 2020-09-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_questionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='text4',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='text5',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='text6',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='text7',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='text8',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='text9',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='additionally',
            field=models.TextField(max_length=4096, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='возраст'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='allergy',
            field=models.TextField(max_length=256, null=True, verbose_name='Наличие аллергии'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='contract',
            field=models.TextField(max_length=64, null=True, verbose_name='Готовность подписать договор'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='friend',
            field=models.TextField(max_length=512, null=True, verbose_name='Наличие друга для крысенка'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='know_how',
            field=models.TextField(max_length=512, null=True, verbose_name='Осведомленность в вопросах содержания'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='location',
            field=models.CharField(max_length=64, null=True, verbose_name='место проживания'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pet_or_breed',
            field=models.TextField(max_length=256, null=True, verbose_name='Любимец или в разведение'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='recommendation',
            field=models.TextField(max_length=256, null=True, verbose_name='Наличие рекомендаций'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='which_baby_rat',
            field=models.CharField(max_length=128, null=True, verbose_name='Какой крысенок интересует'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='ФИО'),
        ),
    ]
