# Generated by Django 3.1.1 on 2020-09-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rattery', '0002_auto_20200911_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='rat',
            name='old_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='старый id'),
        ),
    ]
