# Generated by Django 3.1.1 on 2020-09-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rattery', '0005_auto_20200929_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='email',
            new_name='contact',
        ),
    ]
